version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python /code/myshop/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - ./myshop:/code/myshop
    ports:
      - 8000:8000

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./myshop:/data
    depends_on:
      - web

  celery:
    build:  
      context: .
      dockerfile: Dockerfile
    working_dir: /code/myshop
    command: celery -A myshop worker -l info
    environment:
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./myshop:/code/myshop
    depends_on:
      - web
      - rabbitmq
      - redis
    